# Generated by Django 5.1.3 on 2025-02-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namemodel',
            old_name='name_field',
            new_name='nameF',
        ),
    ]
