# Generated by Django 5.1.3 on 2025-02-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_name_field_namemodel_namef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namemodel',
            old_name='nameF',
            new_name='name_field',
        ),
    ]
